#!/bin/bash

SUDO=

if [ $(test -r /var/run/docker.sock; echo "$?") -ne 0 ]; then
    SUDO="sudo"
fi

$SUDO docker rmi flask-file-upload:latest 2>/dev/null
$SUDO docker build -t flask-file-upload:latest .

$SUDO docker run -it --rm --name flask-file-upload -v ./uploads/:/uploads/ -p 80:80 flask-file-upload
